### ISSUE TITLE
Not working when resend request from developer tool.

### ISSUE THREAD

**Issue by manoj81290** [GramThanos/php-csrf#1]
Hi,
**Situation** : I have list page, on that page I'm calling one model for add or edit data. I'm implementing this library, it works for login flow, but not working for add or edit data using Model (POPUP form) I want to prevent request while re-sending request from developer tool. Please give any Suggestion.

Thanks in advance.

**Comment by GramThanos** [comment]
Check if your setup is right, you may have 2 groups of hashes.

One for login `<?=$csrf->input('login-form');?>` which you validate using `$csrf->validate('login-form')` on login action, and an other one for the popup form `<?=$csrf->input('edit-form');?>` which you validate using `$csrf->validate('edit-form')`.

It would be nice if you could provide an example code so that I can reproduce the problem.

**Comment by GramThanos** [comment]
Closed due to lack of feedback.
