### ISSUE TITLE
Testing invalid CSRF

### ISSUE THREAD

**Issue by unrave1ling** [GramThanos/php-csrf#2]
Hi, i have just implemented this on my pages. However i am clueless on how to test for an invalid CSRF token. I tried using a previously generated CSRF token thinking that it will prevent me from submitting the form but I still managed to submit the form.

Is there anyway to test for invalid CSRF tokens? Thanks.

**Comment by GramThanos** [comment]
The tokens are being created into groups (contexts) so that you can set different tokens for different actions.
Each time you generate a token, you can specify the maximum number of tokens of that context, so that any extra/older token will be deleted. Thus if you want to invalidate older ones you can limit the max number of tokens to 1. The default max number of tokens is 5, thus, by default if you open your form in 6 tabs, the first tab should not work.

For example using the `$csrf->input($context='', $time2Live=-1, $max_hashes=5)`

Allow only 1 token in session, this token will not expire
```php
$csrf->input('context-a', 0, 1)
```

Allow max 5 tokens in this context, this token will be valid for 1 minute
```php
$csrf->input('context-b', 60, 5)
```

**Comment by unrave1ling** [comment]
Thank you for the fast reply! I managed to get it working! :)
