### ISSUE TITLE
Consistency for coding style

### ISSUE THREAD

**Issue by peter279k** [GramThanos/php-csrf#3]
Firstly, thanks for your demo PHP project about CSRF :).

I wonder know what kinds of coding style does this project follow?

And I think it will be good for upcoming commits/PRs to follow style easily :+1: .

**Comment by peter279k** [comment]
@GramThanos, I think we can consider following `PSR-2` or `PSR-12` coding style.

What do you think about this :)?

**Comment by GramThanos** [comment]
I haven't used coding styles on PHP before.
So... I tried porting the library to PSR-12 (can be found on dev branch)... I don't like it :P

I also think this project is too small to define code styles, especially since there are no pull requests.
This is also why I don't think that a namespace is needed #4

**Comment by peter279k** [comment]
Never mind. It's up to you to determine whether coding style is integrated or not :).
